[package]
name = "a03_font_style"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.24.0", features = ["__screenshot"] }
env_logger = "0.10.1"
