[package]
name = "a01_egui_tutorial01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.24.0", features = ["__screenshot"] }
egui = "0.24.0"
env_logger = "0.10.1"
